// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	message "github/charmingruby/habits/internal/device/delivery/queue/message"

	mock "github.com/stretchr/testify/mock"
)

// DeviceQueue is an autogenerated mock type for the DeviceQueue type
type DeviceQueue struct {
	mock.Mock
}

// OnDeviceConnected provides a mock function with given fields: msg
func (_m *DeviceQueue) OnDeviceConnected(msg message.OnDeviceConnectedMessage) error {
	ret := _m.Called(msg)

	if len(ret) == 0 {
		panic("no return value specified for OnDeviceConnected")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(message.OnDeviceConnectedMessage) error); ok {
		r0 = rf(msg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewDeviceQueue creates a new instance of DeviceQueue. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDeviceQueue(t interface {
	mock.TestingT
	Cleanup(func())
}) *DeviceQueue {
	mock := &DeviceQueue{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
