// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	dto "github/charmingruby/habits/internal/device/dto"

	mock "github.com/stretchr/testify/mock"
)

// UseCase is an autogenerated mock type for the UseCase type
type UseCase struct {
	mock.Mock
}

// CreateDevice provides a mock function with given fields: _a0
func (_m *UseCase) CreateDevice(_a0 dto.CreateDeviceInput) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for CreateDevice")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(dto.CreateDeviceInput) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewUseCase creates a new instance of UseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *UseCase {
	mock := &UseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
