name: Test

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24.3
          cache: false

      - name: Install dependencies
        run: |
          go mod tidy

      - name: Install mockery
        uses: vektra/mockery-action@v0.3.0

      - name: Run tests
        run: make tests
